### ISSUE TITLE
Do you offer paid consulting services?

### ISSUE THREAD

**Issue by yongbo** [xvertile/akamai-bmp-generator#9]
Hi.

I want to scrape data from a Android APP and the APP is protected by akamai bmp . 

I tried to generate a `x-acf-sensor-data` by [akamai-bmp-generator](https://github.com/xvertile/akamai-bmp-generator),    it worked very well (I can get the data and the request was not blocked by akamai) . 

But 10 hours later, all of the requests are blocked by akamai (the status code is 403 ).

Could you help me to solve the problem? 

 If you can help solve it, we would like to paid for it. 

Thank You.

**Comment by xvertile** [comment]
I do not offer such services please check
discord.gg/sneakerdev for more advice.

As for what I can offer you is the following:
1. Devices are getting blocked due to the small size that is included.
2. IP blocks
3. Additional cookies / headers blocking you

I highly recomend you join sneakerdev and ask in the #akamai-bmp channel with more context.

**Comment by yongbo** [comment]
thank you very much

**Comment by troypointsyeah** [comment]
Hello, Just want to follow up, how can we get your help on 

Devices are getting blocked due to the small size that is included.
Additional cookies / headers blocking you

Thanks

**Comment by mileessent** [comment]
Hello, Just want to follow up, how can we get your help on

Devices are getting blocked due to the small size that is included.
Additional cookies / headers blocking you

Thanks
